export const TAG_TO_NAME_MAP: Record<number, Record<string, string>> = {
  1: {
    data2: "BPM HEATING TEMP",
    data3: "BPM HEATING TEMP",
    data4: "BPM COOLING TEMP",
    data5: "BPM COOLING TEMP",
    data6: "BPM COOLING TEMP",
    data7: "BPM COOLING TEMP",
    data8: "BPM HEATING TEMP",
    data9: "BPM HEATING TEMP",
  },
  4: {
    data2: "BPM HEATING TEMP",
    data3: "BPM HEATING TEMP",
    data4: "BPM COOLING TEMP",
    data5: "BPM COOLING TEMP",
    data6: "BPM COOLING TEMP",
    data7: "BPM COOLING TEMP",
    data8: "BPM HEATING TEMP",
    data9: "BPM HEATING TEMP",
  },
  2: {
    data2: "PRE HEATING TEMP1",
    data3: "PRE HEATING TEMP2",
    data4: "PRIMER 1 / CLEANING UPPER TEMP",
    data5: "PRIMER 1 / CLEANING OUTSOLE TEMP",
    data6: "PRIMER 2 UPPER TEMP",
    data7: "PRIMER 2 OUTSOLE TEMP",
    data8: "CEMENTING UPPER TEMP",
    data9: "CEMENTING OUTSOLE TEMP",
  },
  5: {
    data2: "PRE HEATING TEMP1",
    data3: "PRE HEATING TEMP2",
    data4: "PRIMER 1 / CLEANING UPPER TEMP",
    data5: "PRIMER 1 / CLEANING OUTSOLE TEMP",
    data6: "PRIMER 2 UPPER TEMP",
    data7: "PRIMER 2 OUTSOLE TEMP",
    data8: "CEMENTING UPPER TEMP",
    data9: "CEMENTING OUTSOLE TEMP",
  },
  3: {
    data2: "CHILLER TEMP 1",
    data3: "CHILLER TEMP 2",
  },
  6: {
    data2: "CHILLER TEMP 1",
    data3: "CHILLER TEMP 2",
  },
};